version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    volumes:
      - ./src:/var/www/html
  
  mysql:
    build: ./mysql
    restart: always
    container_name: "mysql"
    environment:
      MYSQL_DATABASE: php
      MYSQL_USER: ken
      MYSQL_PASSWORD: Nanryou1
      MYSQL_ROOT_PASSWORD: Nanryou1
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: